### ISSUE TITLE
Python PIP requires SSL support

### ISSUE THREAD

**Issue by kianby** [NuTyX/core#37]
I have installed **python-pip** for Python 2. First run indicates **setuptools** is missing:

```
# pip 
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources 
```

After installing **python-setuptools**, I start again **pip** and I get this error:

```
$ pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2457, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2171, in load
    ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 10, in <module>
    from pip.util import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 18, in <module>
    from pip._vendor.distlib import version
  File "/usr/lib/python2.7/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
    from .compat import string_types
  File "/usr/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
```

After some googling it appears that **pip** requires SSL support in Python interpreter. I found this tip to check if SSL is present in Python.

```
$ python
Python 2.7.10 (default, Oct 29 2015, 19:56:25) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> hasattr(socket,"ssl")
False 
```

The problem impacts Python 2 and Python 3.

**Comment by tnut** [comment]
will look at it.
Looks like openssl is a deps of  python-pip
